# Generated by Django 6.0.7 on 2026-07-27 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='daedline',
            new_name='deadline',
        ),
    ]
